name: openvpn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  openvpn:
    runs-on: openvpn-x64
    steps:
      - name: neofetch
        run: |
          neofetch

      - name: iostat
        run: |
          iostat -d


      - name: ls
        run: |
          pwd

      - name: ls
        run: |
          ls -la

      - name: openvpn-config
        run: |
          cat /etc/openvpn/server.conf

      - name: update
        run: |
          ./home/ubuntu/test.sh